### ISSUE TITLE
Sign In Button Error

### ISSUE THREAD

**Issue by bigbird0525** [tableau-mkt/dcm-dfa-wdc#8] opened 2016-11-03 22:23 UTC
Hi,

I was checking out the hosted data connector and the "First, Sign Into Google" button is redirecting to a 404 error. 

- Andrew

**Comment by iamEAP** [comment] 2017-08-28 21:10
Cleaning out the backlog...  This may be a duplicate of #10.

**Closed by iamEAP** 2017-08-28 21:10 UTC
